### ISSUE TITLE
Extension does not use translation file

### ISSUE THREAD

**Issue by frain45** [atik-lab/magento-cookielaw#9]
[Valdecode_CookieLaw.log](https://github.com/atik-lab/magento-cookielaw/files/1611341/Valdecode_CookieLaw.log)
Hello, I use your excellent extension on a couple of sites. It seems that translation files are not processed, despite I put the it_IT translation file in the correct subdirectory.

- Using extension version 1.4
- Translation file name: Valdecode_CookieLaw.csv
- In directory: /app/locale/it_IT

Tests made:
- After uploading the extension, the 3 sentences in the it_IT file provided with the extension remain in English.
- I have updated the it_IT file (attached here), but nothing changes.
- Cache & compilation are disabled; logged out and in after each update.

Notice: changed the translation file extension to .log or Github wouldn't let me upload it here.

[Valdecode_CookieLaw.log](https://github.com/atik-lab/magento-cookielaw/files/1611345/Valdecode_CookieLaw.log)

**Comment by michael-hxx** [comment]
My translations are working fine..

**Comment by atik-lab** [comment]
The it translation is already included and works fine. Did you try any other language like spanish?

**Comment by frain45** [comment]
I answered via email but probably you did not receive it.

I think I found the issue. I added the following inside the <adminthml> tag to \app\code\community\Valdecode\CookieLaw\etc\config.xml:

       <translate>
            <modules>
                <Valdecode_CookieLaw>
                    <files>
                        <default>Valdecode_CookieLaw.csv</default>
                    </files>
                </Valdecode_CookieLaw>
            </modules>
        </translate>

Refreshed the translations cache in Magento, and the module started to use the translation CSV. Only the following remains untranslated: 
- Strings in dropdowns
- The intro "We would like you to review this extension at Magento Connect..." (in system.xml)

Please find the Italian translation file attached, if you want to include it in the package.
[Valdecode_CookieLaw.zip](https://github.com/atik-lab/magento-cookielaw/files/1639074/Valdecode_CookieLaw.zip)

**Comment by atik-lab** [comment]
I didn't understood that the translations that weren't working where in the backend. Thank you very much! I added the code and tested it and it's working fine.
